goodbyes = [
    "Goodbye",
    "Farewell",
    "Adieu",
    "See you later",
    "Until we meet again",
    "Take care",
    "So long",
    "Cheerio",
    "Bye for now",
    "Peace out",
    "Adios",
    "Ciao",
    "Till next time",
    "Catch you later",
    "Toodles",
    "Hasta luego",
    "Auf Wiedersehen",
    "Goodnight",
    "Bye-bye",
    "Arrivederci",
    "Godspeed",
    "Parting is such sweet sorrow",
    "Until next time",
    "Keep in touch",
    "Take it easy",
    "Be well",
    "Cya",
    "Later gator",
]

good_mornings = [
    "Good morning",
    "Morning",
    "Top of the morning to you",
    "Rise and shine",
    "Hello morning",
    "Bonjour",
    "Buongiorno",
    "Guten Morgen",
    "Buenos días",
    "Morning greetings",
    "Wishing you a bright morning",
    "Hello sunshine",
    "A new day begins",
    "Greetings of the day",
    "Salutations",
    "Happy morning",
    "Good day",
    "Sunrise salutations",
    "Wakey, wakey",
    "Start of a new day",
    "Greetings and salutations",
    "Wishing you a cheerful morning",
    "Good vibes in the morning",
    "Morning blessings",
    "Early bird greetings",
    "A bright and beautiful morning to you",
    "Sending you morning smiles",
]

good_afternoons = [
    "Good afternoon",
    "Afternoon",
    "Good day",
    "Hello afternoon",
    "Bonjour",
    "Buon pomeriggio",
    "Guten Tag",
    "Buenas tardes",
    "Afternoon greetings",
    "Wishing you a pleasant afternoon",
    "Greetings of the afternoon",
    "Salutations",
    "Happy afternoon",
    "Hello sunshine",
    "Hope you're having a good day",
    "Enjoy your afternoon",
    "Afternoon blessings",
    "Greetings and salutations",
    "Wishing you a wonderful afternoon",
    "Sending you positive vibes",
    "A bright and beautiful afternoon to you",
    "A sunny afternoon",
    "Wishing you productivity and joy",
    "Afternoon delight",
    "Wishing you a lovely afternoon",
    "Enjoy the rest of your day",
    "Brightening your afternoon",
]

good_evenings = [
    "Good evening",
    "Evening",
    "Good night",
    "Hello evening",
    "Bonjour",
    "Buona sera",
    "Guten Abend",
    "Buenas noches",
    "Evening greetings",
    "Wishing you a pleasant evening",
    "Greetings of the evening",
    "Salutations",
    "Happy evening",
    "Hello moonlight",
    "Hope you're having a good evening",
    "Enjoy your evening",
    "Evening blessings",
    "Greetings and salutations",
    "Wishing you a relaxing evening",
    "Sending you positive vibes",
    "A calm and serene evening to you",
    "A tranquil evening",
    "Wishing you peace and joy",
    "Evening delight",
    "Wishing you a cozy evening",
    "Enjoy the rest of your night",
    "Brightening your evening",
]

good_nights = [
    "Good night",
    "Sweet dreams",
    "Sleep well",
    "Goodnight and sleep tight",
    "Nighty night",
    "Bedtime wishes",
    "Sleep peacefully",
    "Restful night",
    "Dreamland awaits",
    "Wishing you a restful night",
    "Nightfall greetings",
    "Sending you off to dreamland",
    "Wishing you a serene night",
    "Time to hit the hay",
    "Lights out",
    "Sleep with the angels",
    "Nighttime blessings",
    "Starlit dreams",
    "Time to recharge",
    "Sleep under the moonlight",
    "Goodnight kisses",
    "Dream sweetly",
    "Quiet night wishes",
    "Slumber awaits",
    "Till the morning light",
    "Sleep soundly",
    "Nighttime serenity",
    "Wishing you a good night's sleep",
]

welcome_backs = [
    "Welcome back",
    "Nice to see you again",
    "Glad you're back",
    "Welcome back to the team",
    "It's good to have you back",
    "Welcome back, we missed you",
    "You were missed, welcome back",
    "Back in action",
    "Rejoining the crew",
    "Welcome back on board",
    "You've been missed, welcome back",
    "Great to have you back",
    "Happy to see you return",
    "Back and ready to go",
    "Welcome back to the family",
    "You're back, and that's awesome",
    "Welcome back to the fold",
    "It's like you never left",
    "Back in the saddle",
    "Good to see you back",
    "Welcome back, old friend",
    "Reunited and it feels so good",
    "You're back where you belong",
    "Back in familiar territory",
    "Welcome back to the grind",
    "Thrilled to welcome you back",
    "Back and better than ever",
    "Welcome home, once again",
]

at_your_service = [
    "I'm here to assist you",
    "How may I help you?",
    "I'm ready and available",
    "At your disposal",
    "Ready to serve",
    "I'm here for you",
    "How can I assist you today?",
    "Feel free to let me know what you need",
    "I'm at your beck and call",
    "Ready when you are",
    "Here and ready to help",
    "Your wish is my command",
    "Count on me for support",
    "I'm here to lend a hand",
    "Let me know how I can be of service",
    "I'm at your beckon",
    "Ready to tackle any task",
    "How may I be of assistance?",
    "I'm here and ready to support you",
    "Your needs are my priority",
    "Consider me at your service",
    "Tell me what you need, and I'll take care of it",
    "Ready for any requests",
    "I'm here to make things easier for you",
    "Feel free to ask for my help",
    "I'm at your service, 24/7",
    "Here to assist and make things smooth",
    "Count on me to support you",
]